# set(RTAUDIO_API_ASIO true)
set(RTAUDIO_BUILD_TESTING OFF)
set(RTAUDIO_API_JACK OFF)
set(RTAUDIO_API_ALSA OFF)

if (BUILD_SHARED_LIBS)
	set(RTAUDIO_BUILD_STATIC_LIBS OFF)
	set(RTAUDIO_BUILD_SHARED_LIBS ON)
	set(RTAUDIO_STATIC_MSVCRT OFF)
else()
	set(RTAUDIO_BUILD_STATIC_LIBS ON)
	set(RTAUDIO_BUILD_SHARED_LIBS OFF)
	set(RTAUDIO_STATIC_MSVCRT OFF)
endif()

add_subdirectory(external/rtaudio)

set(RtAudio_INCLUDE_DIRS
	external/rtaudio/
	external/rtaudio/include/
)
